config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :phone, :email, :cpf, :birthdate, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :cpf_valid?

  def cpf_valid?
    return if CPF.valid?(cpf)

    errors.add(:cpf)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: "Usuário foi criado com sucesso" }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "Usuário foi editado com sucesso" }
        format.json { render :index, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phone, :email, :cpf, :birthdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(form, field)
    tag.p(form.object.errors[field].try(:first), class: 'invalid-feedback')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark py-3 px-4 mb-5">
      <%= image_tag 'logo' %>
    </nav>
    <div class="container">
      <% if notice.present? %>
        <p class="alert alert-success" style="color: green"><%= notice %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, html: { data: { controller: "masks" } }) do |form| %>
  <div class="row">
    <div class="col-6 card p-3 class">
      <div class="row mb-2">
        <div class="col">
          <%= form.label :name, 'Nome', style: "display: block" %>
          <%= form.text_field :name, class: "form-control" %>
          <%= errors_for(form, :name) %>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col">
          <%= form.label :cpf, 'CPF', style: "display: block" %>
          <%= form.text_field :cpf, class: "form-control", data: { masks_target: 'cpf' } %>
          <%= errors_for(form, :cpf) %>
        </div>
        <div class="col-6">
          <%= form.label :birthdate, 'Data de nasc.', style: "display: block" %>
          <%= form.date_field :birthdate, class: "form-control" %>
          <%= errors_for(form, :birthdate) %>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col">
          <%= form.label :email, style: "display: block" %>
          <%= form.text_field :email, class: "form-control" %>
          <%= errors_for(form, :email) %>
        </div>
        <div class="col">
          <%= form.label :phone, 'Celular', style: "display: block" %>
          <%= form.text_field :phone, class: "form-control", data: { masks_target: 'phone' } %>
          <%= errors_for(form, :phone) %>
        </div>
      </div>
      <div class="mt-3">
        <%= form.submit 'Salvar', class: "btn btn-primary text-white" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr id="<%= dom_id user %>">
  <td><%= user.name %></td>
  <td><%= user.cpf %></td>
  <td><%= user.phone %></td>
  <td><%= user.email %></td>
  <td><%= user.birthdate %></td>
  <td><%= link_to "Editar", edit_user_path(user), class: "btn btn-outline-primary" %></td>
</tr>

app/views/users/edit.html.erb
<div class="d-flex justify-content-between align-items-center w-50">
  <h4>Edição de usuário</h4>
  <%= link_to "Voltar", users_path %>
</div>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h4>Usuários</h4>
  <%= link_to "Novo", new_user_path, class: "btn btn-primary text-white" %>
</div>

<div id="users">
  <table class="table">
    <thead class="table-light">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">Celular</th>
        <th scope="col">Email</th>
        <th scope="col">Data de nascimento</th>
        <th scope="col"></th>
      </tr>
    <tbody>
      <% @users.each do |user| %>
        <%= render user %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="d-flex justify-content-between align-items-center w-50">
  <h4>Novo usuário</h4>
  <div>
    <%= link_to "Voltar", users_path %>
  </div>
</div>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>